services:
  - type: web
    name: cidsauto
    env: node
    buildCommand: npm ci --only=production && npx playwright install-deps && pip3 install -r requirements.txt && npx playwright install chromium
    startCommand: node server.js
    envVars:
      - key: HEADLESS
        value: true
      - key: NODE_ENV
        value: production
      - key: ACTIVE_PROFILE
        value: Akmal
      - key: CIDS_USERNAME
        fromSecret: cids_username
      - key: CIDS_PASSWORD
        fromSecret: cids_password

