services:
  - type: web
    name: cidsauto
    env: node
    buildCommand: npm ci && npx playwright install-deps chromium && pip3 install -r requirements.txt && npx playwright install chromium
    startCommand: node server.js
    envVars:
      - key: HEADLESS
        value: "true"
      - key: NODE_ENV
        value: production
      - key: ACTIVE_PROFILE
        value: Akmal
      - key: PYTHONUNBUFFERED
        value: "1"

